### ISSUE TITLE
implementing pytorch mish inplace

### ISSUE THREAD

**Issue by jpcenteno80** [digantamisra98/Mish#11]
Hi, do you have any tips on how to implement Mish as an inplace operation in PyTorch? Could this work? Is there a way of making the `F.softplus()` operation also inplace?
```
class Mish_(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        softplus_res = F.softplus(x)
        torch.tanh_(softplus_res)
        return x * softplus_res
```

**Comment by digantamisra98** [comment]
Hey. I am still working on the Inplace operation of Mish, however, the issue lies in the TanH inplace implementation. There is an implementation which is somewhat inplace and you can find it here - https://forums.fast.ai/t/meet-mish-new-activation-function-possible-successor-to-relu/53299/89?u=diganta
Please read this thread, it has a subsequent brief discussion about the Inplace operation and possible implementation of Mish.

**Comment by jpcenteno80** [comment]
Thanks. I was running OOM with the "plain" implementation. Will give the implementation you suggest a try.
BTW, I was wondering if there is a typo in the derivative you have in your Mish paper [https://arxiv.org/pdf/1908.08681v1.pdf](https://arxiv.org/pdf/1908.08681v1.pdf), page 2. The delta term shows up as `2e^2x + e^2x + 2` but in Wolfram Alpha I am getting `2e^x + e^2x + 2`. I was testing the code below, but it is not good (not sure why...). It did pass the `torch.autograd.gradcheck` function though.
```
class Mish(torch.autograd.Function):
    @staticmethod
    def forward(ctx, i):
        ctx.save_for_backward(i)
        return i * torch.tanh(F.softplus(i))

    @staticmethod
    def backward(ctx, grad_output):
        i,  = ctx.saved_tensors
        w = 4*(i+1) + 4*torch.exp(2*i) + torch.exp(3*i) + torch.exp(i)*(4*i+6)
        d = 2*torch.exp(i) + torch.exp(2*i) + 2
        return grad_output * torch.exp(i) * w / d**2

class CustomMish(nn.Module):
    def forward(self, input_tensor):
        return Mish.apply(input_tensor)
```

**Comment by digantamisra98** [comment]
Oh thanks for the typo. In the readme, the delta term is correct. I'll take a look at this code and get back to you on the same.

**Comment by digantamisra98** [comment]
@jpcenteno80 Please check this implementation here - https://github.com/thomasbrandon/mish-cuda

**Comment by ildoonet** [comment]
@jpcenteno80 @digantamisra98 Is there any inplaced implementation which is verified for its performance?

**Comment by digantamisra98** [comment]
@ildoonet The only faster (fastest) implementation of Mish whose performance is verified is by Thomas Brandon. Link -  https://github.com/thomasbrandon/mish-cuda
The issue with inplace implementation for Mish arises because of the non-support for inplacing the Tanh operator.
