### ISSUE TITLE
Half the images are missing in Readme

### ISSUE THREAD

**Issue by bluesky314** [digantamisra98/Mish#12]
Title

**Comment by digantamisra98** [comment]
@bluesky314 I didn't understand the issue you're facing?

**Comment by bluesky314** [comment]
In your project description there are alot of images that are missing

**Comment by digantamisra98** [comment]
@bluesky314 All the images are present. Can you please put some clarity of what do you mean by missing? All subsequent images are present in the "Observation" folder both in the repo primary structure and in the notebooks folder. If not clarified, I'll delete this issue.
