### ISSUE TITLE
Double the training time

### ISSUE THREAD

**Issue by drdlfy** [digantamisra98/Mish#14]
My implementation is
inputs = inputs * tf.math.tanh(tf.math.softplus(inputs))
Tensorflow 1.14
When I use this activation function for my own model, the training time is doubled compared to swish

**Comment by digantamisra98** [comment]
@drdlfy Mish is a bit computationally expensive and I am still in the process of optimizing it further. Please take a look at this repository - https://github.com/thomasbrandon/mish-cuda
It has a CUDA implementation which is exponentially faster (Not on double precision and only available for GPU inference)
Mish is getting added to Tensorflow in the addons repository which will be more optimized than my barebone implementation on this repository. I will redirect you to that implementation once it's merged with TF.

**Comment by digantamisra98** [comment]
@drdlfy Mish is added to Tensorflow-Addons, which should be substantially faster than the foundation implementation you've used. Find more details here - https://github.com/tensorflow/addons/tree/master/tensorflow_addons/activations
