### ISSUE TITLE
how to use mish  in  tensorflow slim.conv2d????

### ISSUE THREAD

**Issue by henbucuoshanghai** [digantamisra98/Mish#21]
slim.conv2d    it is relu    ,how to change it to mish?

**Comment by digantamisra98** [comment]
@henbucuoshanghai Hi. I'm not sure how to integrate Mish into TF slim. I'll have to give a check. Meanwhile, you can try integrating TF-Addon's Mish into the TF Slim architecture. Give me some time and I'll get back on this issue. Link to TFA implementation - https://github.com/tensorflow/addons/tree/master/tensorflow_addons/activations#contents

**Comment by henbucuoshanghai** [comment]
very Kind of you

**Comment by digantamisra98** [comment]
@seanpmorgan @WindQAQ

**Comment by seanpmorgan** [comment]
Hi! So TF-Addons is for TF2.x and thus there is no support for the slim library (That was part of `tf.contrib` and is no longer available in TF2).

I think the easiest way to implement it in your existing architecture (given that you have to use slim) would be to write a simple python ops version of mish that you could use:
```
def mish(inputs):
    return inputs * tf.math.tanh(tf.math.softplus(inputs))
```
TF-Addons uses custom-op kernels for CPU/GPU that would give you a noticeable performance increase, but that is non-trival to incorporate into your code base  (likely not worth the effort, but depends on your use case.)

**Comment by digantamisra98** [comment]
@henbucuoshanghai hopefully, this solved your issue. Closing this as of now. Feell free to re-open.
