### ISSUE TITLE
Computational cost of Mish vs GELU vs Swish

### ISSUE THREAD

**Issue by DonaldTsang** [digantamisra98/Mish#25]
What are the computational cost (CPU/GPU cycles per node) of Mish vs GELU vs Swish?
If it is possible to reduce the CPU/GPU cycles of the computation through simplification,
it can save both time and energy, leading to lower green house gas emissions.
Of course convergence is important, RELU isn't that computational heavy, but it is weak,
and right now the second derivative of both GELU and Swish are symmetric.

**Comment by digantamisra98** [comment]
Mish is more computationally cheaper than GELU. Using device optimized code like [CUDA_Mish](https://github.com/thomasbrandon/mish-cuda) for GPU and [CPU_mish](https://github.com/digantamisra98/Mish/blob/107cfa5b46efd052e330f1c46c9f0f276fedd31e/Mish/Torch_dev/functional.py#L25) have made it significantly faster and cheaper to compute. There's an active issue thread discussing about this in detail which you can find [here](https://github.com/digantamisra98/Mish/issues/22). 
Closing this thread as of now. Feel free to re-open it if you have any other questions. Thanks!

**Comment by hiyyg** [comment]
@digantamisra98 Well, in my experiments, speed: `mish` < `mish-cuda`~`nn.SiLU` < `nn.GELU`.

**Comment by digantamisra98** [comment]
@hiyyg it depends on what form of GELU you're using. As referred in the paper, if you use the exact form, it's pretty slow. Also could you post your results including: Hardware, Executed Script, Forward And Backward pass timings. Thanks!

**Comment by hiyyg** [comment]
@digantamisra98 I use `nn.GELU` from pytorch. I run 3 exps simultaneously wrt. `nn.SiLU`, `nn.GELU`, `mish-cuda` on machine with 4 TITAN X GPUs, `mish-cuda` and `nn.SiLU` take about 14 hours, while `nn.GELU` takes about 12 hours. I also tested a memory efficient `Mish` from [here](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/activations_me.py#L88), but it was much slower.

**Comment by hiyyg** [comment]
Well, on another machine with 2080Ti GPUs, the difference is smaller. The speed of `nn.SiLU`, `nn.GELU` and `mish-cuda` is almost the same.

**Comment by digantamisra98** [comment]
@hiyyg There are many contributing factors. 1. PyTorch, I assume, doesn't use the exact form of GELU. 2. Memory Efficient Mish isn't supposed to be faster, it's supposed to use less memory and since it's written on Pytorch sub optimally, anything written on the low level C++ kernels would be much faster.
