### ISSUE TITLE
Extended Coverage of other CNNs

### ISSUE THREAD

**Issue by DonaldTsang** [digantamisra98/Mish#26]
(As a side note)
There are papers that noted information regarding the larger variety of CNNs for ImageNet testing.
- https://github.com/BertMoons/Comparing-CNN-Architectures
  - https://www.researchgate.net/publication/328490160_Embedded_Deep_Neural_Networks_Algorithms_Architectures_and_Circuits_for_Always-on_Neural_Network_Processing
- https://github.com/CeLuigi/models-comparison.pytorch
  - https://arxiv.org/pdf/1810.00736.pdf
- https://github.com/yeephycho/nasnet-tensorflow
  - https://arxiv.org/pdf/1707.07012.pdf

**Comment by digantamisra98** [comment]
ImageNet training is way too costly for compute and I don't have the resources to do the same so unfortunately I won't be pursuing on benchmarking networks on ImageNet.
