### ISSUE TITLE
Discussion regarding GAN benchmarks

### ISSUE THREAD

**Issue by DonaldTsang** [digantamisra98/Mish#27]
For starters I would like to mention that https://github.com/kozistr/Awesome-GANs and https://github.com/nightrome/really-awesome-gan exists for people to check references.

**Comment by digantamisra98** [comment]
GANs or any additional benchmarks are not in my priority list. I'm more interested in exploring the theory aspects of why Mish is better. Empirical benchmarks can go only so far to prove the robustness of an activation function so I don't think it makes much sense to have extensive benchmarks on many architectures out there.
