### ISSUE TITLE
Application of Mish on ReXNet

### ISSUE THREAD

**Issue by VRandme** [digantamisra98/Mish#34]
[ReXNet: Diminishing Representational Bottleneck on Convolutional Neural Network](https://github.com/clovaai/rexnet)
This paper addresses representational bottleneck in a network and proposes new design principles.
The authors apply this method on MobileNetV1 and V2 and gain performance that scales much better than EfficientNets

One of the tools they use is Swish. In this instance, they actually provide theoretical and empirical justification for this. (This involves the rank of inputs and outputs, and is explained within the paper)

The authors do not discuss or use Mish however, which is shown to be better in extensive use cases.

Since the ReXNet is quite simple, it would seem to be relatively straight forward to conduct studies investigating the replacement of swish with mish in the relevant settings.

I hope this is of interest to you.

**Comment by digantamisra98** [comment]
Yes, I came across this paper a couple of days ago. I'm inclined towards testing Mish on this architecture however I don't have the compute resources for ImageNet experiments allocated for Mish as of now.

**Comment by digantamisra98** [comment]
Since, I don't have access to any compute now and it won't be possible for me to run this model, I'm closing the issue as of now but will keep this on my checklist to run whenever I have access to a cluster. Thanks!
