### ISSUE TITLE
Need help with Mish-Metal

### ISSUE THREAD

**Issue by philipturner** [digantamisra98/Mish#39]
I read your research paper on Mish, and from the graphs I saw, it is clearly the best activation function.

You had two different implementations of Mish with widely different computational overheads. There were standard Mish and Mish-CUDA, where Mish-CUDA has almost zero computational cost. I'm optimizing DL4S for Metal, and looking to optimize Mish so that it can be the top-recommended function. However, I need to know how you implemented Mish-CUDA.

Could you please explain how Mish-CUDA was faster than the standard Mish, and how I might implement it in a generic GPGPU context? I have a lot of experience with assembly-level optimization and I know the differences between Apple GPUs/Metal and Nvidia GPUs/CUDA well, if that helps with your explanation.

**Comment by digantamisra98** [comment]
@philipturner Thanks for reaching out. Unfortunately I wasn't primarily involved in the dev of Mish-CUDA. The best person to answer your queries would be @thomasbrandon. But considering Mish is already available in PyTorch native, you should go through the codebase of the torch implementation as well.

**Comment by philipturner** [comment]
Thanks for responding so quickly! Implementing Mish is still far in the future, as I'm going to (hopefully not) have to rewrite DL4S from the ground up for GPU. I didn't know where to find code for Mish-CUDA in your repo, so thanks for the pointer. I'll look at it when I get around to implementing Mish, and heavily optimize it myself. I'll put in more effort to optimizing Mish than anything else because of how awesome it is.

I'm also in a similar situation with you when it comes to getting the word out about novel discoveries. I think that my work, [ARHeadsetKit](https://github.com/philipturner/ARHeadsetKit), is in a similar situation to yours 2 years ago. Would you mind looking over my research paper on [scene color reconstruction](https://github.com/philipturner/scene-color-reconstruction) since I looked at yours? I also have [an article](https://philipturner.github.io/first-affordable-ar-headset), although that's more combined content than your research paper so it wouldn't be a fair request.

One last request, I think I emailed you previously about my involvement in DL4S. When you asked @palle-k to implement Mish, you said you hoped to contribute to DL4S in the future. Now would be a better time than ever. Is there anything else you think you could contribute?

**Comment by philipturner** [comment]
The source code was very helpful and I just scanned it. It's not that complicated, and it does something interesting with computing gradients that likely causes the speed boost.

**Comment by digantamisra98** [comment]
@philipturner Thanks for the feedback. Sure, I'll be happy to read your work and let you know my thoughts on the same. Re: DL4S, while I believe supporting Metal will be really interesting, I'm a bit unsure about my bandwidth for contribution to the project probably up until the Winter break. But I'll be happy to be in the loop and help in any way possible. 

Re: Mish-CUDA: yes, as far as I understand correctly, the gradients are sort of cached so as to save buffer time (but I'm not sure and I'm not an expert on this). 

Re: The email: Sorry, lot of emails to go through. Issues would be a better place to discuss.

**Comment by philipturner** [comment]
That's okay! I figured you wouldn't have much capacity to contribute, but I still wanted you to be part of it. I feel like I'm in the same situation as you, trying to get the word out about a personal discovery (Mish or ARHeadsetKit). It's also really cool to be working with the engineer of the theoretically most optimal activation function in existence.

Would you mind changing your repository visibility to public? Go to the "People" section of DL4S Team and it should say "Private" next to your name with a drop down

**Comment by digantamisra98** [comment]
@philipturner I'll try my best to help maximally as I can. And yes I can understand spreading the word of a novel work is not easy but once you tell it to a few people it will spread like a chain reaction. So it's just a matter of time and I wish the best for you. Also I won't be confident on claiming that Mish is the most optimal function but it's cool to see the works which have benefited because of it and I aim to make it's benefits more theoretically grounded. 

Sure, just changed to public. Thanks!

**Comment by philipturner** [comment]
Thank you so much for your insight! It's been an honor talking to you!
