### ISSUE TITLE
Issue about Table.1

### ISSUE THREAD

**Issue by LeungWaiHo** [digantamisra98/Mish#40]
Dear authors:
Thanks for your contribution in activation functions.
Now I have a question about a statistical index "mean loss" in Table.1. Could you please tell me what the meaning is?
Thanks again. And looking forward to your reply.

**Comment by digantamisra98** [comment]
@LeungWaiHo it corresponds to the mean of the final validation loss recorded across the 23 runs for that table. Let me know if you still have any questions.

**Comment by LeungWaiHo** [comment]
@digantamisra98 "validation loss" means the error percentage on the validation dataset or other items?

**Comment by digantamisra98** [comment]
Just on validation dataset, yes.
