### ISSUE TITLE
Which CNN architecture is considered for the experimentation of "Test accuracy versus initializers"?

### ISSUE THREAD

**Issue by MeenalNarkhede** [digantamisra98/Mish#43]
The repository compares Mish and Swish activation functions against different initializers in terms of test accuracy for the CIFAR 10 dataset. What is the CNN architecture for which these results are observed?

**Comment by digantamisra98** [comment]
I don't think I have that experiment folder with me anymore but as far as I recall for the ablation studies that were presented in v2 of the paper including the one you mentioned - impact of initializers on performance were all down on custom 4-layered standard CNN architecture. 
Sorry for not being able to provide the most accurate information. But I believe the observation presented should be consistent when using other architectures.
