### ISSUE TITLE
Saving trained model (mish-Keras)

### ISSUE THREAD

**Issue by senovr** [digantamisra98/Mish#9]
Hi, I am trying to save weights of trained model utilizing Keras model_checkpoint.

The error I am getting (last couple of rows):

File "C:\Users\SParkhonyuk\AppData\Local\Continuum\anaconda3\envs\DL\lib\site-packages\keras\engine\network.py", line 860, in get_config
    layer_config = layer.get_config()

  File "C:\Users\SParkhonyuk\repos\...\mish.py", line 36, in get_config
    return dict(list(base_config.items()) + list(config.items()))

NameError: name 'config' is not defined

Some global configuration is missing in mish.py ( in fact, it is a straightforward function).

Can you please direct me to what exactly needs to be added to make the model save-able?

**Comment by digantamisra98** [comment]
Hey @senovr. Thank you for pointing it out. It was a minor issue. The config dictionary is present when we have a list of trainable parameters for the activation function. Since, Mish doesn't have any, there is no config object. I have fixed the code. Please try now, hopefully it will work.

**Comment by senovr** [comment]
Hey @digantamisra98 

Another feedback from my side on Mish:

I tried also enable tensorboard in Keras callbacks.
It fails with the newest implementation.

I tried defining the function right in the file where my CNN is stored; it doesn't help.
It even brokes model_checkpoint routine again.

After some search on Google, I found this issue:
https://github.com/keras-team/keras/issues/8716

When I re-implemented mish in a manner described above, both tensorboard and model_checkpoints callback are working now.

Maybe you can consider re-writing mish.py?

PS:
the code snippet is as follows:

import keras.backend as K
from keras.utils.generic_utils import get_custom_objects

# ------------------------------------------------------------
# needs to be defined as activation class otherwise error
# AttributeError: 'Activation' object has no attribute '__name__'    
class Mish(Activation):
    
    def __init__(self, activation, **kwargs):
        super(Mish, self).__init__(activation, **kwargs)
        self.__name__ = 'Mish'

def mish(x):
    return x*K.tanh(K.softplus(x))

get_custom_objects().update({'Mish': Mish(mish)}) 
# ------------------------------------------------------------

**Comment by digantamisra98** [comment]
@senovr Thanks for pointing this out. Earlier I was following the Layer implementation as shown in the advanced activation function module of keras as shown here: https://github.com/keras-team/keras/blob/master/keras/layers/advanced_activations.py
I have fixed the code as per your recommendation. Hopefully, everything works now.
Let me know. Will close this once you have given the heads up that it runs.

**Comment by xuzhang5788** [comment]
@senovr 
I used your class, but when I import mish, I got 

Failed to convert object of type <class 'function'> to Tensor. Contents: <function Mish.mish at 0x7f92975d6bf8>. Consider casting elements to a supported type.

I changed this into swish, like this 

from keras import backend as K
from keras.utils.generic_utils import get_custom_objects
from keras.layers.core import Dense, Dropout, Activation

# ------------------------------------------------------------
# needs to be defined as activation class otherwise error
# AttributeError: 'Activation' object has no attribute '__name__'    
class Swish(Activation):
    
    def __init__(self, activation, **kwargs):
        super(Swish, self).__init__(activation, **kwargs)
        self.__name__ = 'swish'

    def swish(x):
        return (K.sigmoid(x) * x)

    get_custom_objects().update({'swish': Swish(swish)})
I saved above as swish_keras.py
when I use from swish_keras import Swish
I got 

name 'Swish' is not defined

**Comment by xuzhang5788** [comment]
@senovr 
I found my errors. there is no space before def swish(x) and get_custom_objects().update({'swish': Swish(swish)})

@digantamisra98 I tried your updated mish.py, it works. Thank you.

**Comment by digantamisra98** [comment]
@senovr @xuzhang5788 closing this issue since it seems to have been resolved.
